### ISSUE TITLE
Error when trying to run sonar-scanner command

### ISSUE THREAD

**Issue by tazihosniomar** [insideapp-oss/sonar-apple#62]
Issue Description:
Error when trying to run sonar-scanner.

Command executed:
sonar-scanner

Complete output when running sonar-scanner, including the stack trace and command used:
sonar-scanner
INFO: Scanner configuration file: /Users/otazihosni/sonar-scanner/conf/sonar-scanner.properties
INFO: Project root configuration file: /Users/otazihosni/Documents/Workspace/cs_aoc_appofcard/ios/sonar-project.properties
INFO: SonarScanner 4.7.0.2747
INFO: Java 11.0.14.1 Eclipse Adoptium (64-bit)
INFO: Mac OS X 12.3 x86_64
INFO: User cache: /Users/otazihosni/.sonar/cache
INFO: Scanner configuration file: /Users/otazihosni/sonar-scanner/conf/sonar-scanner.properties
INFO: Project root configuration file: /Users/otazihosni/Documents/Workspace/cs_aoc_appofcard/ios/sonar-project.properties
INFO: Analyzing on SonarQube server 9.8.0.63668
INFO: Default locale: "fr_FR", source code encoding: "UTF-8"
INFO: Load global settings
INFO: Load global settings (done) | time=217ms
INFO: Server id: 147B411E-AYXEDHUzDfraOlGr0hIz
INFO: User cache: /Users/otazihosni/.sonar/cache
INFO: Load/download plugins
INFO: Load plugins index
INFO: Load plugins index (done) | time=187ms
INFO: Load/download plugins (done) | time=292ms
INFO: Process project properties
INFO: Process project properties (done) | time=8ms
INFO: Execute project builders
INFO: Execute project builders (done) | time=1ms
INFO: Project key: fr.sephora.aoc
INFO: Base dir: /Users/otazihosni/Documents/Workspace/cs_aoc_appofcard/ios
INFO: Working dir: /Users/otazihosni/Documents/Workspace/cs_aoc_appofcard/ios/.scannerwork
INFO: Load project settings for component key: 'fr.sephora.aoc'
INFO: Load project settings for component key: 'fr.sephora.aoc' (done) | time=168ms
INFO: Load quality profiles
INFO: Load quality profiles (done) | time=242ms
INFO: Load active rules
INFO: Load active rules (done) | time=4755ms
INFO: Load analysis cache
INFO: Load analysis cache (404) | time=164ms
WARN: Property 'sonar.password' is deprecated. It will not be supported in the future. Please instead use the 'sonar.login' parameter with a token.
INFO: Load project repositories
INFO: Load project repositories (done) | time=163ms
INFO: Indexing files...
INFO: Project configuration:
WARN: File '/Users/otazihosni/Documents/Workspace/cs_aoc_appofcard/ios/xcodebuild.log' is bigger than 20MB and as consequence is removed from the analysis scope.
WARN: File '/Users/otazihosni/Documents/Workspace/cs_aoc_appofcard/ios/Pods/CS_iOS_SDK/ContentsquareModule.xcframework/ios-arm64_x86_64-simulator/dSYMs/ContentsquareModule.framework.dSYM/Contents/Resources/DWARF/ContentsquareModule' is bigger than 20MB and as consequence is removed from the analysis scope.
WARN: File '/Users/otazihosni/Documents/Workspace/cs_aoc_appofcard/ios/Pods/GoogleMaps/Maps/Frameworks/GoogleMapsCore.framework/GoogleMapsCore' is bigger than 20MB and as consequence is removed from the analysis scope.
WARN: File '/Users/otazihosni/Documents/Workspace/cs_aoc_appofcard/ios/Pods/GoogleMaps/Maps/Frameworks/GoogleMaps.framework/GoogleMaps' is bigger than 20MB and as consequence is removed from the analysis scope.
WARN: File '/Users/otazihosni/Documents/Workspace/cs_aoc_appofcard/ios/Pods/GoogleMaps/Base/Frameworks/GoogleMapsBase.framework/GoogleMapsBase' is bigger than 20MB and as consequence is removed from the analysis scope.
WARN: File '/Users/otazihosni/Documents/Workspace/cs_aoc_appofcard/ios/Pods/Batch/Batch.xcframework/ios-arm64_arm64e_armv7/Batch.framework/Batch' is bigger than 20MB and as consequence is removed from the analysis scope.
WARN: File '/Users/otazihosni/Documents/Workspace/cs_aoc_appofcard/ios/Pods/KlarnaMobileSDK/ios/XCFramework/full/universal/KlarnaMobileSDK.xcframework.zip' is bigger than 20MB and as consequence is removed from the analysis scope.
WARN: File '/Users/otazihosni/Documents/Workspace/cs_aoc_appofcard/ios/Pods/KlarnaMobileSDK/ios/XCFramework/full/universal/KlarnaMobileSDK.xcframework/ios-arm64_i386_x86_64-simulator/dSYMs/KlarnaMobileSDK.framework.dSYM/Contents/Resources/DWARF/KlarnaMobileSDK' is bigger than 20MB and as consequence is removed from the analysis scope.
WARN: File '/Users/otazihosni/Documents/Workspace/cs_aoc_appofcard/ios/Pods/KlarnaMobileSDK/ios/XCFramework/full/universal/KlarnaMobileSDK.xcframework/ios-arm64_armv7/KlarnaMobileSDK.framework/KlarnaMobileSDK' is bigger than 20MB and as consequence is removed from the analysis scope.
WARN: File '/Users/otazihosni/Documents/Workspace/cs_aoc_appofcard/ios/Pods/GoogleAppMeasurement/Frameworks/GoogleAppMeasurement.framework/GoogleAppMeasurement' is bigger than 20MB and as consequence is removed from the analysis scope.
WARN: File '/Users/otazihosni/Documents/Workspace/cs_aoc_appofcard/ios/Pods/SwiftLint/swiftlint' is bigger than 20MB and as consequence is removed from the analysis scope.
INFO: 2393 files indexed
INFO: 20250 files ignored because of scm ignore settings
INFO: Quality profile for css: Sonar way
INFO: Quality profile for js: Sonar way
INFO: Quality profile for json: Sonar way
INFO: Quality profile for objc: Objective-C
INFO: Quality profile for swift: Swift
INFO: Quality profile for yaml: Sonar way
INFO: ------------- Run sensors on module AOC
INFO: Load metrics repository
INFO: Load metrics repository (done) | time=214ms
INFO: Sensor JaCoCo XML Report Importer [jacoco]
INFO: 'sonar.coverage.jacoco.xmlReportPaths' is not defined. Using default locations: target/site/jacoco/jacoco.xml,target/site/jacoco-it/jacoco.xml,build/reports/jacoco/test/jacocoTestReport.xml
INFO: No report imported, no coverage information will be imported by JaCoCo XML Report Importer
INFO: Sensor JaCoCo XML Report Importer [jacoco] (done) | time=12ms
INFO: Sensor IaC CloudFormation Sensor [iac]
INFO: 0 source files to be analyzed
INFO: 0/0 source files have been analyzed
INFO: Sensor IaC CloudFormation Sensor [iac] (done) | time=920ms
INFO: Sensor IaC Kubernetes Sensor [iac]
INFO: 0 source files to be analyzed
INFO: 0/0 source files have been analyzed
INFO: Sensor IaC Kubernetes Sensor [iac] (done) | time=551ms
INFO: Sensor Swift Sensor [sonarapple]
INFO: Analyzing source files
WARN: Unexpected error creating text range on file fr.sephora.aoc:Common/Common/Tools/Factories.swift for token \( on (144, 22) -  (144, 22)
java.lang.IllegalArgumentException: Start pointer [line=144, lineOffset=22] should be before end pointer [line=144, lineOffset=22]
	at org.sonar.api.utils.Preconditions.checkArgument(Preconditions.java:43)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newRangeValidPointers(DefaultInputFile.java:365)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newRange(DefaultInputFile.java:306)
	at fr.insideapp.sonarqube.apple.commons.antlr.HighlighterVisitor.fillContext(HighlighterVisitor.java:127)
	at fr.insideapp.sonarqube.swift.antlr.SwiftHighlighterVisitor.fillContext(SwiftHighlighterVisitor.java:120)
	at fr.insideapp.sonarqube.apple.commons.antlr.CustomTreeVisitor.fillContext(CustomTreeVisitor.java:52)
	at fr.insideapp.sonarqube.apple.commons.antlr.ParseTreeAnalyzer.analyze(ParseTreeAnalyzer.java:65)
	at fr.insideapp.sonarqube.swift.SwiftSensor.execute(SwiftSensor.java:50)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:64)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:88)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:61)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:79)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:61)
	at org.sonar.scanner.scan.SpringModuleScanContainer.doAfterStart(SpringModuleScanContainer.java:82)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
	at org.sonar.scanner.scan.SpringProjectScanContainer.scan(SpringProjectScanContainer.java:401)
	at org.sonar.scanner.scan.SpringProjectScanContainer.scanRecursively(SpringProjectScanContainer.java:397)
	at org.sonar.scanner.scan.SpringProjectScanContainer.doAfterStart(SpringProjectScanContainer.java:366)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
	at org.sonar.scanner.bootstrap.SpringGlobalContainer.doAfterStart(SpringGlobalContainer.java:135)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)

WARN: Unexpected error creating text range on file fr.sephora.aoc:Common/Common/Tools/Factories.swift for token \( on (144, 42) -  (144, 42)
java.lang.IllegalArgumentException: Start pointer [line=144, lineOffset=42] should be before end pointer [line=144, lineOffset=42]
	at org.sonar.api.utils.Preconditions.checkArgument(Preconditions.java:43)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newRangeValidPointers(DefaultInputFile.java:365)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newRange(DefaultInputFile.java:306)
	at fr.insideapp.sonarqube.apple.commons.antlr.HighlighterVisitor.fillContext(HighlighterVisitor.java:127)
	at fr.insideapp.sonarqube.swift.antlr.SwiftHighlighterVisitor.fillContext(SwiftHighlighterVisitor.java:120)
	at fr.insideapp.sonarqube.apple.commons.antlr.CustomTreeVisitor.fillContext(CustomTreeVisitor.java:52)
	at fr.insideapp.sonarqube.apple.commons.antlr.ParseTreeAnalyzer.analyze(ParseTreeAnalyzer.java:65)
	at fr.insideapp.sonarqube.swift.SwiftSensor.execute(SwiftSensor.java:50)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:64)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:88)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:61)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:79)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:61)
	at org.sonar.scanner.scan.SpringModuleScanContainer.doAfterStart(SpringModuleScanContainer.java:82)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
	at org.sonar.scanner.scan.SpringProjectScanContainer.scan(SpringProjectScanContainer.java:401)
	at org.sonar.scanner.scan.SpringProjectScanContainer.scanRecursively(SpringProjectScanContainer.java:397)
	at org.sonar.scanner.scan.SpringProjectScanContainer.doAfterStart(SpringProjectScanContainer.java:366)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
	at org.sonar.scanner.bootstrap.SpringGlobalContainer.doAfterStart(SpringGlobalContainer.java:135)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)

WARN: Unexpected error creating text range on file fr.sephora.aoc:AppOfCards/Application/Coordinators/Coordinator.swift for token if on (64, 8) -  (64, 6)
java.lang.IllegalArgumentException: Start pointer [line=64, lineOffset=8] should be before end pointer [line=64, lineOffset=6]
	at org.sonar.api.utils.Preconditions.checkArgument(Preconditions.java:43)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newRangeValidPointers(DefaultInputFile.java:365)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newRange(DefaultInputFile.java:306)
	at fr.insideapp.sonarqube.apple.commons.antlr.HighlighterVisitor.fillContext(HighlighterVisitor.java:127)
	at fr.insideapp.sonarqube.swift.antlr.SwiftHighlighterVisitor.fillContext(SwiftHighlighterVisitor.java:120)
	at fr.insideapp.sonarqube.apple.commons.antlr.CustomTreeVisitor.fillContext(CustomTreeVisitor.java:52)
	at fr.insideapp.sonarqube.apple.commons.antlr.ParseTreeAnalyzer.analyze(ParseTreeAnalyzer.java:65)
	at fr.insideapp.sonarqube.swift.SwiftSensor.execute(SwiftSensor.java:50)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:64)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:88)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:61)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:79)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:61)
	at org.sonar.scanner.scan.SpringModuleScanContainer.doAfterStart(SpringModuleScanContainer.java:82)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
	at org.sonar.scanner.scan.SpringProjectScanContainer.scan(SpringProjectScanContainer.java:401)
	at org.sonar.scanner.scan.SpringProjectScanContainer.scanRecursively(SpringProjectScanContainer.java:397)
	at org.sonar.scanner.scan.SpringProjectScanContainer.doAfterStart(SpringProjectScanContainer.java:366)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
	at org.sonar.scanner.bootstrap.SpringGlobalContainer.doAfterStart(SpringGlobalContainer.java:135)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)

Environment:
Apple M1 Max
macOS Monterey Version 12.3
SonarQube: 8.9.10
sonar-apple-plugin-0.2.1
java version: 17.0.5.

Thanks in advance for your help.

**Comment by gaelfoppolo** [comment]
Hi tazihosniomar,
This does not look like an issue for the plugin, but rather from the launch of SonarQube itself.
Your Java version is 17 and SonarQube needs Java 11.

Here some references I found about your issue. Could you take a look? Please tell us if this solves your issue.
https://community.sonarsource.com/t/this-site-cant-be-reached-after-running-sonar-sh-start/62587
https://github.com/Homebrew/discussions/discussions/2746

**Comment by gaelfoppolo** [comment]
Any update @tazihosniomar?

**Comment by danielepantaleone** [comment]
I'm having the same issue. I tried to install OpenJDK 11 and Oracle JDK 11 but if I do so SonarQube won't event start.

**Comment by danielepantaleone** [comment]
Diggin a bit deeper in our source code I found that these type of errors are thrown only when sonar scanner is parsing source files containing emojis:

<img width="261" alt="Screenshot 2023-03-20 at 11 13 52" src="https://user-images.githubusercontent.com/1245124/226310160-de0f8591-357e-4587-94a9-2fa577444c0f.png">

**Comment by gaelfoppolo** [comment]
Indeed! Maybe because some emojis are defined with several codepoints, which mess up with the token index provided by ANTLR. Eg: https://emojipedia.org/emoji/%E2%84%B9/

**Comment by gaelfoppolo** [comment]
We'll have to take a deeper look to understand and fix the issue.
This is just a warning and only affect the highlight part on Sonar.
I understand this is not optimal to get theses warning logs, but since this does not affect the analysis itself, this is a just noise.

**Comment by rounak-codiant** [comment]
I'm also facing an error.

**Command:** `sonar-scanner`

**Logs:** 

```
INFO: Scanner configuration file: /usr/local/Cellar/sonar-scanner/4.7.0.2747/libexec/conf/sonar-scanner.properties
INFO: Project root configuration file: /path/to/project/sonar-project.properties
INFO: SonarScanner 4.7.0.2747
INFO: Java 11.0.16 Homebrew (64-bit)
INFO: Mac OS X 13.3.1 x86_64
INFO: User cache: /path/.sonar/cache
INFO: Scanner configuration file: /usr/local/Cellar/sonar-scanner/4.7.0.2747/libexec/conf/sonar-scanner.properties
INFO: Project root configuration file: /path/to/project/sonar-project.properties
INFO: Analyzing on SonarQube server 9.9.0.65466
INFO: Default locale: "en_US", source code encoding: "UTF-8"
INFO: Load global settings
INFO: Load global settings (done) | time=181ms
INFO: Server id: B6A44B8D-Example_hFkxHLiql3eQ
INFO: User cache: /path/.sonar/cache
INFO: Load/download plugins
INFO: Load plugins index
INFO: Load plugins index (done) | time=94ms
INFO: Load/download plugins (done) | time=443ms
INFO: Process project properties
INFO: Process project properties (done) | time=10ms
INFO: Execute project builders
INFO: Execute project builders (done) | time=2ms
INFO: Project key: Test-Project
INFO: Base dir: /path/to/project
INFO: Working dir: /path/to/project/.scannerwork
INFO: Load project settings for component key: 'Test-Project'
INFO: Load quality profiles
INFO: Load quality profiles (done) | time=150ms
INFO: Load active rules
INFO: Load active rules (done) | time=2077ms
INFO: Load analysis cache
INFO: Load analysis cache (404) | time=10ms
INFO: Load project repositories
INFO: Load project repositories (done) | time=19ms
INFO: Indexing files...
INFO: Project configuration:
INFO: 2320 files indexed
INFO: 0 files ignored because of scm ignore settings
INFO: Quality profile for json: Sonar way
INFO: Quality profile for objc: Objective-C
INFO: Quality profile for swift: SwiftLint (outdated copy since April 27 2023 at 05:06 pm)
INFO: ------------- Run sensors on module Project-iOS-test
INFO: Load metrics repository
INFO: Load metrics repository (done) | time=55ms
INFO: Sensor IaC CloudFormation Sensor [iac]
INFO: 0 source files to be analyzed
INFO: 0/0 source files have been analyzed
INFO: Sensor IaC CloudFormation Sensor [iac] (done) | time=321ms
INFO: Sensor IaC Kubernetes Sensor [iac]
INFO: 0 source files to be analyzed
INFO: 0/0 source files have been analyzed
INFO: Sensor IaC Kubernetes Sensor [iac] (done) | time=104ms
INFO: Sensor Swift Sensor [sonarapple]
INFO: Analyzing source files
```

Not moving further from this, waited for half an hour and tried multiple times.

**Comment by gaelfoppolo** [comment]
Hi @rounak-codiant,
Please create your own issue, using the template, so we can help you.

**Comment by TomaszLizer** [comment]
I am experiencing similar issue with `WARN` Unexpected error creating text range.
```
WARN: Unexpected error creating text range on file ios-appointment-module-test:Sources/PaymentModule/PaymentTransaction/ViewModel/NewIssueRefundViewModel.swift for token \( on (171, 63) -  (171, 63)
java.lang.IllegalArgumentException: Start pointer [line=171, lineOffset=63] should be before end pointer [line=171, lineOffset=63]
	at org.sonar.api.utils.Preconditions.checkArgument(Preconditions.java:43)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newRangeValidPointers(DefaultInputFile.java:365)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newRange(DefaultInputFile.java:306)
	at fr.insideapp.sonarqube.apple.commons.antlr.HighlighterVisitor.fillContext(HighlighterVisitor.java:127)
	at fr.insideapp.sonarqube.swift.antlr.SwiftHighlighterVisitor.fillContext(SwiftHighlighterVisitor.java:122)
	at fr.insideapp.sonarqube.apple.commons.antlr.CustomTreeVisitor.fillContext(CustomTreeVisitor.java:52)
	at fr.insideapp.sonarqube.apple.commons.antlr.ParseTreeAnalyzer.analyze(ParseTreeAnalyzer.java:65)
	at fr.insideapp.sonarqube.swift.SwiftSensor.execute(SwiftSensor.java:65)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:64)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:88)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:61)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:79)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:61)
	at org.sonar.scanner.scan.SpringModuleScanContainer.doAfterStart(SpringModuleScanContainer.java:82)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
	at org.sonar.scanner.scan.SpringProjectScanContainer.scan(SpringProjectScanContainer.java:401)
	at org.sonar.scanner.scan.SpringProjectScanContainer.scanRecursively(SpringProjectScanContainer.java:397)
	at org.sonar.scanner.scan.SpringProjectScanContainer.doAfterStart(SpringProjectScanContainer.java:366)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
	at org.sonar.scanner.bootstrap.SpringGlobalContainer.doAfterStart(SpringGlobalContainer.java:135)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:126)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:81)
	at org.sonarsource.scanner.cli.Main.main(Main.java:62)
```
It is quite frustrating since upon code inspection nothing special seems to be hiding there (usually just whitespace) and there is quite a lot of such output making log un-readable :/
